config/routes.rb
TicTacToe::Application.routes.draw do
  resources :moves

  root :to => 'moves#index'

end

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :position, :letter

  validates_uniqueness_of :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
    @move = Move.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moves }
    end
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
    @move = Move.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @move }
    end
  end

  # GET /moves/new
  # GET /moves/new.json
  def new
    @move = Move.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @move }
    end
  end

  # GET /moves/1/edit
  def edit
    @move = Move.find(params[:id])
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(params[:move])

    respond_to do |format|
      if @move.save
        format.html { redirect_to root_url, notice: 'Move was successfully created.' }
        format.json { render json: @move, status: :created, location: @move }
      else
        format.html { render action: "new" }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moves/1
  # PUT /moves/1.json
  def update
    @move = Move.find(params[:id])

    respond_to do |format|
      if @move.update_attributes(params[:move])
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move = Move.find(params[:id])
    @move.destroy

    respond_to do |format|
      format.html { redirect_to moves_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moves/_form.html.erb
<%= form_for(@move) do |f| %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% @move.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <b>Please select your Letter:</b>

  <div>
    <%= f.label :letter %>
    <%= f.select :letter, ['X', 'O'] %>
  </diV>

  <b>Make your Move!!</b> 

  <div>
    <%= f.label :position %>
    <%= f.select :position, ['1', '2', '3', '4', '5', '6', '7', '8', '9'] %>
  </div>

  <div class="actions">
    <%= f.submit "Place Move" %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<h1>Tic-Tac-Toe</h1>

<table id="board">
  <tbody>
    <tr>
      <td>1
        <% @moves.each do |move| %>
          <% if move.position.to_i == 1 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
      <td>2
        <% @moves.each do |move| %>
          <% if move.position.to_i == 2 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
      <td>3
        <% @moves.each do |move| %>
          <% if move.position.to_i == 3 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>4
        <% @moves.each do |move| %>
          <% if move.position.to_i == 4 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
      <td>5
        <% @moves.each do |move| %>
          <% if move.position.to_i == 5 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
      <td>6
        <% @moves.each do |move| %>
          <% if move.position.to_i == 6 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr> 
      <td>7
        <% @moves.each do |move| %>
          <% if move.position.to_i == 7 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
      <td>8
        <% @moves.each do |move| %>
          <% if move.position.to_i == 8 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
      <td>9
        <% @moves.each do |move| %>
          <% if move.position.to_i == 9 %>
            <%= move.letter %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<br />

<%= render 'form' %>

<h3>Game History:</h3>
<table>
<tr>
  <th>Position</th>
  <th>Letter</th>
</tr>

<% @moves.each do |move| %>
  <tr>
    <td><%= move.position %></td>
    <td><%= move.letter %></td>
    <td><%= link_to 'Destroy', move, method: :delete %></td>
  </tr>
<% end %>

</table>

app/views/moves/new.html.erb
<h1>New move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Position:</b>
	<%= @move.position %>
</p>

<p>
	<b>Letter:</b>
	<%= @move.letter %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>